<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Modules</name>
   <tag></tag>
   <elementGuidId>d14d5335-db73-433a-9d05-9ae1968862dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='modules-wrapper__btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f06d295b-30ac-4da8-9f54-36717fdd8eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-th</value>
      <webElementGuid>7f268797-123f-44e3-989e-01581d3d5c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modules-wrapper__btn&quot;)/i[@class=&quot;fa fa-th&quot;]</value>
      <webElementGuid>c5ec79f4-7f6d-4d21-b534-2d1c95b6a313</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='modules-wrapper__btn']/i</value>
      <webElementGuid>eb68d938-8b4b-4af1-9ef5-072a95828918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/i</value>
      <webElementGuid>a3523d52-14ee-4c84-a22a-8479ab07028f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
