<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table Elements</name>
   <tag></tag>
   <elementGuidId>294a9332-68da-41d0-bf81-f1dbd4b11279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-dashboard-order//p-table//td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>6b6fde4b-402e-4833-a380-9dec889f14f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1674485223107</value>
      <webElementGuid>e1815db4-5550-4652-9dcb-b0e23bd80b68</webElementGuid>
   </webElementProperties>
</WebElementEntity>
