<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table Elements</name>
   <tag></tag>
   <elementGuidId>4426dd19-ac3b-496b-a1f0-ea7a02455fa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-dashboard-delivery//p-table//td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>17f24631-663a-42ef-b13a-b00d9d23eade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1674485223107</value>
      <webElementGuid>34777735-369c-4452-91aa-a356098b22b3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
