<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_User</name>
   <tag></tag>
   <elementGuidId>20186540-6621-48b2-8ce9-0a687f7a117f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Meyer Pascal  (Chargeur) ' or . = 'Meyer Pascal  (Chargeur) ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aa1a2be48861-0 > div.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c3dc0a2f-b011-4513-834d-8ccf919e7462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>a38650a0-c698-4c34-95a6-8d9dc4ff9b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Meyer Pascal  (Chargeur) </value>
      <webElementGuid>4063eda0-6115-4a4e-8349-676f41fd4328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aa1a2be48861-0&quot;)/div[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>1dedcb50-0daf-486f-944f-beb16028a27f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[(text() = 'Meyer Pascal  (Chargeur) ' or . = 'Meyer Pascal  (Chargeur) ')]</value>
      <webElementGuid>ade6ccb2-3790-4be7-8b31-8706decbe31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select user...'])[1]/following::div[6]</value>
      <webElementGuid>d3b0f298-ab30-4499-9e19-dc76b872e04c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mytower2018+pascal.meyer@gmail.com'])[1]/preceding::div[1]</value>
      <webElementGuid>b4c2d16b-a9a3-4314-829f-fe7a335822bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Meyer Pascal']/parent::*</value>
      <webElementGuid>42aea3f8-7a20-44a2-830d-ffbeea3752da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>e94fadc4-e4eb-4ed6-bc98-a3828f5568ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Meyer Pascal  (Chargeur) ' or . = 'Meyer Pascal  (Chargeur) ')]</value>
      <webElementGuid>7f7fc4bb-4c96-4bc0-9a50-9f2185d6adda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
