<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Creation Date (Date To)</name>
   <tag></tag>
   <elementGuidId>50db1309-0fdb-4c82-8b58-fe5dff330e5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;corp&quot;]/app-corp/app-dashboard-order/div/app-delivery-search/app-collapsible-panel/div/div[2]/app-advanced-form-search/form/div/div[17]/div/div[2]/div/div/app-datetime-picker/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ea7e941-d679-469c-a58b-21a11e5abb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-picker-input ng-valid ng-touched ng-dirty</value>
      <webElementGuid>469355aa-944d-4b9f-80cf-15e1f3f9628e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>c3729ba6-4281-4b2f-8f42-80820d8f4726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-dashboard-order[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper app-padding&quot;]/app-delivery-search[1]/app-collapsible-panel[@class=&quot;advanced-search&quot;]/div[@class=&quot;collapsible-panel panel panel-visible&quot;]/div[@class=&quot;panel-body body-table body-search  body-search&quot;]/app-advanced-form-search[1]/form[@class=&quot;form-horizontal ng-untouched ng-valid ng-star-inserted ng-dirty&quot;]/div[@class=&quot;row d-flex-w&quot;]/div[@class=&quot;col-md-4 form-group mgtop ng-star-inserted&quot;]/div[@class=&quot;nochpadding&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;custom&quot;]/app-datetime-picker[@class=&quot;ng-untouched ng-valid ng-dirty&quot;]/div[@class=&quot;col-md-12 nopadding date-picker_wrapper&quot;]/div[1]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control date-picker-input ng-valid ng-touched ng-dirty&quot;]</value>
      <webElementGuid>a82521bb-d9ea-449b-aad9-74aa14f61134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-dashboard-order/div/app-delivery-search/app-collapsible-panel/div/div[2]/app-advanced-form-search/form/div/div[17]/div/div[2]/div/div/app-datetime-picker/div/div/div/input</value>
      <webElementGuid>1ea1a59f-c159-443b-a5b3-ea2a4ff84079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div[2]/div/div/app-datetime-picker/div/div/div/input</value>
      <webElementGuid>3e13a6f5-8f57-4f00-ae33-32c135a5d113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>adc21339-3cef-466d-bfa3-dee527a13da6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
