<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_item2</name>
   <tag></tag>
   <elementGuidId>0bfc3751-3e90-4c14-b46d-3732b30eda44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;corp&quot;]/app-corp/app-dashboard-order/div/app-delivery-search/app-collapsible-panel/div/div[2]/app-advanced-form-search/form/div/div[15]/div/div[2]/div/app-old-autocomplete/ng-select/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ng-select.ng-select.ng-select-typeahead.ng-select-multiple.ng-select-searchable.ng-select-clearable.ng-valid.ng-select-bottom.ng-touched.ng-dirty.ng-select-focused.ng-select-opened > div.ng-select-container.ng-has-value > div.ng-value-container > div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>735983ae-49fd-4597-ac4d-ba1c32014e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>4f608925-131f-4116-90ec-d43393a030c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9ba5865-4faf-4517-8707-c5a5d469bd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fac271f5-a18f-4e01-b037-e86b89ed7b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3f568377-3a05-48e6-b34a-1ebdfb7214cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>ae79593243ee</value>
      <webElementGuid>cde3004f-b7ca-4fc5-a2d9-7c61e159aa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc632247-7cd8-42be-b351-526f5c793e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>ae79593243ee</value>
      <webElementGuid>3ee18126-808f-4f04-a8e8-7fdf822e7e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-dashboard-order[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper app-padding&quot;]/app-delivery-search[1]/app-collapsible-panel[@class=&quot;advanced-search&quot;]/div[@class=&quot;collapsible-panel panel panel-visible&quot;]/div[@class=&quot;panel-body body-table body-search  body-search&quot;]/app-advanced-form-search[1]/form[@class=&quot;form-horizontal ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;row d-flex-w&quot;]/div[@class=&quot;col-md-4 form-group mgtop ng-star-inserted&quot;]/div[@class=&quot;nochpadding&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-old-autocomplete[1]/ng-select[@class=&quot;ng-select ng-select-typeahead ng-select-multiple ng-select-searchable ng-select-clearable ng-valid ng-select-bottom ng-touched ng-dirty ng-select-focused ng-select-opened&quot;]/div[@class=&quot;ng-select-container ng-has-value&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>aaecffa9-0bd5-4eec-9a0e-f0b0a8d887b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[16]</value>
      <webElementGuid>59b74a94-220d-4c2b-91c6-310fb2e9ea23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-dashboard-order/div/app-delivery-search/app-collapsible-panel/div/div[2]/app-advanced-form-search/form/div/div[15]/div/div[2]/div/app-old-autocomplete/ng-select/div/div/div[3]/input</value>
      <webElementGuid>1b86c6fc-42a9-474f-be62-6b937faa26a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/app-old-autocomplete/ng-select/div/div/div[3]/input</value>
      <webElementGuid>3aef9351-85da-4dfe-96f0-7f75c8506cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>d7c295c9-e5ba-4305-ade1-2939099d9125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
