<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Month_date_To2</name>
   <tag></tag>
   <elementGuidId>6cdd7c76-6719-4603-83c2-39bb63a3d4a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;corp&quot;]/app-corp/app-dashboard-order/div/app-delivery-search/app-collapsible-panel/div/div[2]/app-advanced-form-search/form/div/div[19]/div/div[2]/div/div/app-datetime-picker/div/div/div/ngb-datepicker/div[1]/ngb-datepicker-navigation/ngb-datepicker-navigation-select/select[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.custom-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9e181d24-92ff-4344-8279-84abffd7ffe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select month</value>
      <webElementGuid>ed6a2ea2-32c6-4eed-89cc-1ba52921dcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>fb02cc81-1e83-4098-a8c0-57672685718a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select month</value>
      <webElementGuid>84c10827-98b1-4bbb-8b34-c16bd25451bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JanFebMarAprMayJunJulAugSepOctNovDec</value>
      <webElementGuid>75ccd21b-0451-4eec-ac28-c837904f66cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-dashboard-order[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper app-padding&quot;]/app-delivery-search[1]/app-collapsible-panel[@class=&quot;advanced-search&quot;]/div[@class=&quot;collapsible-panel panel panel-visible&quot;]/div[@class=&quot;panel-body body-table body-search  body-search&quot;]/app-advanced-form-search[1]/form[@class=&quot;form-horizontal ng-untouched ng-valid ng-star-inserted ng-dirty&quot;]/div[@class=&quot;row d-flex-w&quot;]/div[@class=&quot;col-md-4 form-group mgtop ng-star-inserted&quot;]/div[@class=&quot;nochpadding&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;custom&quot;]/app-datetime-picker[@class=&quot;ng-untouched ng-valid ng-dirty&quot;]/div[@class=&quot;col-md-12 nopadding date-picker_wrapper&quot;]/div[1]/div[@class=&quot;input-group&quot;]/ngb-datepicker[@class=&quot;dropdown-menu show ng-star-inserted&quot;]/div[@class=&quot;ngb-dp-header&quot;]/ngb-datepicker-navigation[@class=&quot;ng-star-inserted&quot;]/ngb-datepicker-navigation-select[@class=&quot;ngb-dp-navigation-select ng-star-inserted&quot;]/select[@class=&quot;custom-select&quot;]</value>
      <webElementGuid>f7d20960-554e-4fc2-a57d-fce59619f531</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-dashboard-order/div/app-delivery-search/app-collapsible-panel/div/div[2]/app-advanced-form-search/form/div/div[19]/div/div[2]/div/div/app-datetime-picker/div/div/div/ngb-datepicker/div/ngb-datepicker-navigation/ngb-datepicker-navigation-select/select</value>
      <webElementGuid>8bd2ce9c-da51-4089-88b3-3d15378ab7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Date (Date To) :'])[1]/following::select[1]</value>
      <webElementGuid>61c99664-b440-43c2-b5ae-f688acabf7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Date (Date From) :'])[1]/following::select[1]</value>
      <webElementGuid>1c8a76cf-c523-44f5-af44-bf404c5f5add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mo'])[1]/preceding::select[2]</value>
      <webElementGuid>c5529870-685a-41b2-b013-378645b0fcb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tu'])[1]/preceding::select[2]</value>
      <webElementGuid>82af34b9-894b-4d16-b016-e4bb5e0998bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9f18975e-a67e-402d-9a56-a370bd74a9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'Select month' and (text() = 'JanFebMarAprMayJunJulAugSepOctNovDec' or . = 'JanFebMarAprMayJunJulAugSepOctNovDec')]</value>
      <webElementGuid>9026b930-337f-4b16-b62d-34aced6d0cfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
